<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master" %>

<%@ Import Namespace="EmpManagement.App_Code.Services" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="FormBodyContent" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="True" DataKeyNames="Id"
        DataSourceID="ObjectDataSource2" AutoGenerateEditButton="True" AutoGenerateDeleteButton="True">
    </asp:GridView>
    <br />
    <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="Create.aspx">New</asp:HyperLink>
    <asp:ObjectDataSource ID="ObjectDataSource2" runat="server"
        SelectMethod="GetAll" TypeName="EmpManagement.App_Code.Services.DepartmentService"
        DataObjectTypeName="EmpManagement.App_Code.Models.Department" ConflictDetection="OverwriteChanges"
        DeleteMethod="Delete" InsertMethod="Insert" UpdateMethod="Update" />
</asp:Content>
